// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBndpsQCfln9ln85ffh9LZf1Y8TnpKExJk',
    appId: '1:948660682878:web:f635a28baef63aa13b582f',
    messagingSenderId: '948660682878',
    projectId: 'echo-test-type',
    authDomain: 'echo-test-type.firebaseapp.com',
    storageBucket: 'echo-test-type.firebasestorage.app',
    measurementId: 'G-4BJRC2KXVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmWs2Yqld_nWL1_55QTq9SZaqYg_89IMQ',
    appId: '1:948660682878:android:dcd256bcbd601f273b582f',
    messagingSenderId: '948660682878',
    projectId: 'echo-test-type',
    storageBucket: 'echo-test-type.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZTqr0TK61OYgmOwwD7dAcIVIjJFH359A',
    appId: '1:948660682878:ios:644bb2037c8243023b582f',
    messagingSenderId: '948660682878',
    projectId: 'echo-test-type',
    storageBucket: 'echo-test-type.firebasestorage.app',
    iosBundleId: 'com.example.echoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZTqr0TK61OYgmOwwD7dAcIVIjJFH359A',
    appId: '1:948660682878:ios:644bb2037c8243023b582f',
    messagingSenderId: '948660682878',
    projectId: 'echo-test-type',
    storageBucket: 'echo-test-type.firebasestorage.app',
    iosBundleId: 'com.example.echoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBndpsQCfln9ln85ffh9LZf1Y8TnpKExJk',
    appId: '1:948660682878:web:4b74969dfd4abe153b582f',
    messagingSenderId: '948660682878',
    projectId: 'echo-test-type',
    authDomain: 'echo-test-type.firebaseapp.com',
    storageBucket: 'echo-test-type.firebasestorage.app',
    measurementId: 'G-DTK14F3RKK',
  );
}
